import useTextDirection from "../useTextDirection";
import { NextIntlClientProvider, useMessages } from "next-intl";

import type { Metadata } from "next";
import localFont from "next/font/local";

import Header from "@/components/Header/Header";
import Footer from "@/components/Footer/Footer";
import HelpCenter from "@/components/HelpCenter/HelpCenter";
import CategoryBar from "@/components/CategoryBar/CategoryBar";

import "swiper/css";
import "./globals.css";

const pingAR = localFont({
  src: "../../../public/assets/fonts/PingARRegular.otf",
  variable: "--font-pingAR",
});

const pingARBold = localFont({
  src: "../../../public/assets/fonts/PingARBold.otf",
  variable: "--font-bold",
});

const pingARMedium = localFont({
  src: "../../../public/assets/fonts/PingARMedium.otf",
  variable: "--font-medium",
});

const pingARBlack = localFont({
  src: "../../../public/assets/fonts/PingARHeavy.otf",
  variable: "--font-extrabold",
});

export const metadata: Metadata = {
  title: "Sam Valley",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
  params: { locale },
}: Readonly<{
  children: React.ReactNode;
  params: { locale: string };
}>) {
  const direction = useTextDirection(locale);
  const messages = useMessages();

  return (
    <html lang={locale} dir={direction}>
      <head>
        <link
          rel="stylesheet"
          type="text/css"
          charSet="UTF-8"
          href="https://cdnjs.cloudflare.com/ajax/libs/slick-carousel/1.6.0/slick.min.css"
        />
        <link
          rel="stylesheet"
          type="text/css"
          href="https://cdnjs.cloudflare.com/ajax/libs/slick-carousel/1.6.0/slick-theme.min.css"
        />
      </head>
      <body
        className={`text-primary ${pingAR.variable} ${pingARBold.variable} ${pingARMedium.variable} ${pingARBlack.variable} font-normal font`}>
        <NextIntlClientProvider locale={locale} messages={messages}>
          <Header />
          <CategoryBar />
          <main className="bg-cloud min-h-screen">{children}</main>
          <HelpCenter />
          <Footer />
        </NextIntlClientProvider>
      </body>
    </html>
  );
}
